### ISSUE TITLE
Не выкидывается исключение если параметр минимального баланса некорректен

### ISSUE THREAD

**Issue by Yliannasko** [abashkaev/Team_project_JavaQA#1]
# Описание
Не выкидывается исключение вида IllegalArgumentException, если мин. баланс больше макс. баланса.

# Локация дефекта
https://github.com/abashkaev/Team_project_JavaQA/blob/e9bd6a6945b63f925c77cba1b0d0073004e63966/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть класс SevingAccountTest
2. Перейти к тесту shouldTestMinBalanceMoreMaxBalance
3. Создать объект SavingAccount класса со ставкой minBalance =100, maxBalance = 80
4. Запуск теста на вывод исключения

_Ожидаемый результат:_ Выпадает исключение "Минимальный баланс не может быть больше максимального"
_Фактический результат:_ Тест не проходит, исключение не выпадает. 

# Вставка кода

 https://github.com/abashkaev/Team_project_JavaQA/blob/62097f349a9f2f2c4046d2da8e0956d3b93ed34d/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L19-L25

# Окружение
Операционная система: Windows 11 Pro
IDE: Intellig IDEA Community Edition 2023.1
Java: Open JDK 11

**Comment by abashkaev** [comment]
Добавил исключения если минимальный баланс, больше максимального и если минимальный баланс меньше нуля

https://github.com/abashkaev/Team_project_JavaQA/blob/ac572821ae9dad4c856ad85aca7012d274722376/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L39-L43

https://github.com/abashkaev/Team_project_JavaQA/blob/ac572821ae9dad4c856ad85aca7012d274722376/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L49-L53

**Comment by Yliannasko** [comment]
По результатам тестирования метод SavingAccount на вывод исключений  работает корректно. Добавлены тесты на добавленные исключения.
