### ISSUE TITLE
Неправильный расчет процентов в методе yearChange, при положительном балансе

### ISSUE THREAD

**Issue by abashkaev** [abashkaev/Team_project_JavaQA#10]
# Описание
При вызове метода `yearChange`, при положительном балансе, производится неправильный расчет процентов. 

# Локация дефекта
https://github.com/abashkaev/Team_project_JavaQA/blob/258bf25cad2491e26d34b6ddf66250b8edd0ec0f/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L74-L84

# Воспроизведение
1. Открыть код программы в IDEA
2. Создать объект типа CreditAccount, с начальным балансом 1000 и ставкой 15
3. Вызываем метод `yearChange`
4. Запускаем программу

ОР: Метод выдает ответ "0" (так как баланс положительный  
ФР: Метод выдает ответ "150"

# Тест
https://github.com/abashkaev/Team_project_JavaQA/blob/258bf25cad2491e26d34b6ddf66250b8edd0ec0f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L57-L62

# Окружение
IDE: IntelliJ IDEA 2023.1 (Community Edition) (Build #IC-231.8109.175, built on March 28, 2023)
ОС: Windows 11 (22H2, 22621.1702)
Java: OpenJDK11

**Comment by Yliannasko** [comment]
Внесены поправки в метод yearChange. Тест работает правильно.
https://github.com/abashkaev/Team_project_JavaQA/blob/44e88ed4f777843f291acbd8eaadf4aea87d0c7a/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L100-L112

**Comment by abashkaev** [comment]
Все отлично, тест проходит.
