### ISSUE TITLE
Неправильный расчет при вызове метода add

### ISSUE THREAD

**Issue by abashkaev** [abashkaev/Team_project_JavaQA#11]
# Описание
При вызове метода `add`, возвращается переменная `amount`, хотя она должна прибавляться в `balance`

# Локация дефекта
https://github.com/abashkaev/Team_project_JavaQA/blob/e9bd6a6945b63f925c77cba1b0d0073004e63966/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L54-L72

# Воспроизведение
1. Запустить программу
2. Создать объект `CreditAccount ` c начальным балансом 1000 и не отрицательной ставкой
3. Вызвать метод` add(3000)`
4. Вызвать `getBalance`
5. Запустить программу

ОР:  Ответ 4000 (1000 начальные + 3000 пополнение)
ФР:  Ответ 3000

# Тест
https://github.com/abashkaev/Team_project_JavaQA/blob/258bf25cad2491e26d34b6ddf66250b8edd0ec0f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L8-L15

# Окружение
IDE: IntelliJ IDEA 2023.1 (Community Edition) (Build #IC-231.8109.175, built on March 28, 2023)
ОС: Windows 11 (22H2, 22621.1702)
Java: OpenJDK11

**Comment by Yliannasko** [comment]
Внесены поправки в метод. Тест работает.
https://github.com/abashkaev/Team_project_JavaQA/blob/44e88ed4f777843f291acbd8eaadf4aea87d0c7a/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82-L89

**Comment by abashkaev** [comment]
Все корректно, тест проходит
