### ISSUE TITLE
Баланс выходит за пределы кредитного лимита при использовании метода pay

### ISSUE THREAD

**Issue by abashkaev** [abashkaev/Team_project_JavaQA#12]
# Описание
При использовании метода `pay`, баланс выходит за пределы кредитного лимита.

# Локация дефекта
https://github.com/abashkaev/Team_project_JavaQA/blob/e9bd6a6945b63f925c77cba1b0d0073004e63966/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L31-L52

# Воспроизведение
1. Открыть код программы в IDEA
2.  Создать объект типа `CreditAccount`, c начальным балансом 0 и кредитным лимитом 5000
3. Добавьте метод `pay`, с суммой 6000
4. Вызовете метода `getBalance`

ОР: Метод вернул сумму без изменений (0), так как произошел выход за пределы кредитного лимита
ФР: Баланс изменился на сумму покупки (-6000)

# Тест
https://github.com/abashkaev/Team_project_JavaQA/blob/3a700a995f8e719547940cfc013a6b2991e308cf/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L83-L90

# Окружение
IDE: IntelliJ IDEA 2023.1 (Community Edition) (Build #IC-231.8109.175, built on March 28, 2023)
ОС: Windows 11 (22H2, 22621.1702)
Java: OpenJDK11

**Comment by Yliannasko** [comment]
Внесены поправки в метод. Тест работает.
https://github.com/abashkaev/Team_project_JavaQA/blob/44e88ed4f777843f291acbd8eaadf4aea87d0c7a/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L53-L67

**Comment by abashkaev** [comment]
При исправлении данной проблемы, возникла ситуация, когда сумма покупки больше кредитного лимита, и при этом не учитывается изначальный баланс.
https://github.com/abashkaev/Team_project_JavaQA/blob/89c4e5e99f1716d824a3898c5b1653c9ac34fd4e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L60-L64

Добавлен тест на проверку таких случаев
https://github.com/abashkaev/Team_project_JavaQA/blob/89c4e5e99f1716d824a3898c5b1653c9ac34fd4e/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L123-L129

**Comment by Yliannasko** [comment]
Внесены поправки в метод Pay. 
https://github.com/abashkaev/Team_project_JavaQA/blob/6b280dc6e39fa51287e55f79832eb09acad5ba19/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L56-L66

**Comment by abashkaev** [comment]
Принято, все отлично!
