### ISSUE TITLE
Неправильный расчет баланса в методе pay

### ISSUE THREAD

**Issue by abashkaev** [abashkaev/Team_project_JavaQA#13]
# Описание
При использовании метода `pay`, не правильно считается итоговый баланс.

# Локация дефекта
https://github.com/abashkaev/Team_project_JavaQA/blob/e9bd6a6945b63f925c77cba1b0d0073004e63966/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L45-L50

# Воспроизведение 
1. Открыть код программы в IDEA
2. Создать объект типа CreditAccount, с начальным балансом 1500 и ставкой 15
3. Вызвать метод `pay(500)`
4. Вызвать метод `getBalance`

ОР: Метод вернул 1000 (Изначальный баланс минус сумма покупки)
ФР: Метод вернул -500

# Тест
https://github.com/abashkaev/Team_project_JavaQA/blob/3a700a995f8e719547940cfc013a6b2991e308cf/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L91-L98

# Окружение
IDE: IntelliJ IDEA 2023.1 (Community Edition) (Build #IC-231.8109.175, built on March 28, 2023)
ОС: Windows 11 (22H2, 22621.1702)
Java: OpenJDK11

**Comment by Yliannasko** [comment]
Внесены поправки в метод. Тест работает.
https://github.com/abashkaev/Team_project_JavaQA/blob/44e88ed4f777843f291acbd8eaadf4aea87d0c7a/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L53-L67

**Comment by abashkaev** [comment]
Тест работает. Баланс в данном случае считается корректно. Необходимо доработать метод pay, уточнения [тут](https://github.com/abashkaev/Team_project_JavaQA/issues/12#issuecomment-1584543593)
