### ISSUE TITLE
Отсутствуют исключения в конструкторе CreditAccount

### ISSUE THREAD

**Issue by abashkaev** [abashkaev/Team_project_JavaQA#14]
# Описание
В конструкторе `CreditAccount(int initialBalance, int creditLimit, int rate)` отсутствует проверка на отрицательные значения для переменных `initialBalance` и `creditLimit`. Это может привести к некорректной инициализации объекта `CreditAccount `с отрицательными значениями начального баланса баланса и лимита кредита.

# Локация дефекта
https://github.com/abashkaev/Team_project_JavaQA/blob/e9bd6a6945b63f925c77cba1b0d0073004e63966/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L12-L29

# Воспроизведение
1. Создать объект типа `CreditAccount`, с отрицательными значениями для начального баланса и кредитного лимита
2. Вызвать любой метод

ОР: При передаче отрицательных значений в `initialBalance` или `creditLimit` должно возникать исключение `IllegalArgumentException` с соответствующим сообщением об ошибке.
ФР: Объект создается без исключений

# Тест
https://github.com/abashkaev/Team_project_JavaQA/blob/5b8338dc9e85038c8974f51191e6e17052890155/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L101-L108

# Окружение
IDE: IntelliJ IDEA 2023.1 (Community Edition) (Build #IC-231.8109.175, built on March 28, 2023)
ОС: Windows 11 (22H2, 22621.1702)
Java: OpenJDK11

**Comment by Yliannasko** [comment]
Внесены поправки в метод на вывод недостающих исключений. Тесты проходят.
https://github.com/abashkaev/Team_project_JavaQA/blob/44e88ed4f777843f291acbd8eaadf4aea87d0c7a/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L21-L41

**Comment by abashkaev** [comment]
В условии указанно наличие проверки на отрицательные числа, 0 можно использовать

**Comment by abashkaev** [comment]
Исключения добавлены, и работают корректно, спасибо!
