### ISSUE TITLE
Не выкидывается исключение, если параметр начального баланса некорректен

### ISSUE THREAD

**Issue by Yliannasko** [abashkaev/Team_project_JavaQA#2]
# Описание
Не выкидывается исключение вида IllegalArgumentException, если начальный баланс меньше нуля.

# Локация дефекта
https://github.com/abashkaev/Team_project_JavaQA/blob/e9bd6a6945b63f925c77cba1b0d0073004e63966/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть класс SevingAccountTest
2. Перейти к тесту shouldTestInitialBalanceLess0
3. Создать объект SavingAccount класса со ставкой initialBalance = -100
4. Запуск теста на вывод исключения

_Ожидаемый результат:_ Начальный баланс не может быть отрицательным, а у вас: -100
_Фактический результат:_ Тест не проходит, исключение не выпадает

# Вставка кода
https://github.com/abashkaev/Team_project_JavaQA/blob/62097f349a9f2f2c4046d2da8e0956d3b93ed34d/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L64-L70

# Окружение
Операционная система: Windows 11 Pro
IDE: Intellig IDEA Community Edition 2023.1
Java: Open JDK 11

**Comment by abashkaev** [comment]
Добавил исключение на параметр начального баланса

https://github.com/abashkaev/Team_project_JavaQA/blob/ac572821ae9dad4c856ad85aca7012d274722376/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L34-L38

**Comment by Yliannasko** [comment]
По результатам тестирования метод SavingAccount на вывод исключений  работает корректно. Добавлен тест на исключение если initialBalance < 0.
