### ISSUE TITLE
Не выкидывается исключение, если параметр процентной ставки некорректен

### ISSUE THREAD

**Issue by Yliannasko** [abashkaev/Team_project_JavaQA#3]
# Описание
Не выкидывается исключение вида IllegalArgumentException, если процентная ставка отрицательная.

# Локация дефекта
https://github.com/abashkaev/Team_project_JavaQA/blob/e9bd6a6945b63f925c77cba1b0d0073004e63966/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть класс SevingAccountTest
2. Перейти к тесту shouldTestWhenRateLess0
3. Создать объект SavingAccount класса со ставкой rate =-15
4. Запуск теста на вывод исключения

_Ожидаемый результат:_ Накопительная ставка не может быть отрицательной, а у вас: -15
_Фактический результат:_ Тест не проходит, исключение не выпадает

# Вставка кода

  https://github.com/abashkaev/Team_project_JavaQA/blob/62097f349a9f2f2c4046d2da8e0956d3b93ed34d/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L9-L17

# Окружение
Операционная система: Windows 11 Pro
IDE: Intellig IDEA Community Edition 2023.1
Java: Open JDK 11

**Comment by abashkaev** [comment]
Исключение работает, код не менял, прошу ретест или уточнение

**Comment by Yliannasko** [comment]
По результатам тестирования метод SavingAccount на вывод исключений  работает корректно
