### ISSUE TITLE
После пополнение счета, значение баланса приравнивается значению пополнения 

### ISSUE THREAD

**Issue by Yliannasko** [abashkaev/Team_project_JavaQA#4]
# Описание
При пополнении баланса, сумма которого не выходит за пределы максимального баланса, значение баланса приравнивается значению пополнения

# Локация дефекта
https://github.com/abashkaev/Team_project_JavaQA/blob/ac572821ae9dad4c856ad85aca7012d274722376/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L72

# Шаги воспроизведения
1. Открыть класс SevingAccountTest
2. Перейти к тесту shouldAddLessThanMaxBalance
3. Создать объект SavingAccount класса со ставкой 
4. initialBalance =2_000,
    minBalance =1_000,
    maxBalance=10_000,
    amount = 3_000
5. Запуск теста на проверку ожидаемого результата initialBalance(2_000)+amount(3_000)

_Ожидаемый результат:_ Баланс пополнился expected =5_000
_Фактический результат:_ Баланс равен сумме пополнения actual=3_000

# Вставка кода

https://github.com/abashkaev/Team_project_JavaQA/blob/62097f349a9f2f2c4046d2da8e0956d3b93ed34d/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L73-L86

# Окружение
Операционная система: Windows 11 Pro
IDE: Intellig IDEA Community Edition 2023.1
Java: Open JDK 11

**Comment by abashkaev** [comment]
Поправил метод, тест проходит

https://github.com/abashkaev/Team_project_JavaQA/blob/7b1c1c6aed1ff18fd8c579dc4df5a034cd11a8c1/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L97-L107

**Comment by Yliannasko** [comment]
По результатам тестирования метод Add работает корректно
