### ISSUE TITLE
Покупка допускается если значение баланса выходит за границы допустимого минимального баланса

### ISSUE THREAD

**Issue by Yliannasko** [abashkaev/Team_project_JavaQA#5]
# Описание
Допускается совершение покупки на сумму, значение которого выводит баланс за границы допустимого минимального баланса. 

# Локация дефекта
https://github.com/abashkaev/Team_project_JavaQA/blob/e9bd6a6945b63f925c77cba1b0d0073004e63966/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения
1. Открыть класс SevingAccountTest
2. Перейти к тесту shouldTestWhenBalanceGoBeyondTheMinBalance
3. Создать объект SavingAccount класса со ставкой 
4. initialBalance =2_000,
    minBalance =1_000,
    maxBalance=10_000,
    amount = 1_500
5. Запуск теста на проверку ожидаемого результата initialBalance(2_000)-amount(1_500)

_Ожидаемый результат:_ Баланс должен остаться без изменения expected =2_000
_Фактический результат:_ Покупка совершается без ограничений actual=500

# Вставка кода

https://github.com/abashkaev/Team_project_JavaQA/blob/62097f349a9f2f2c4046d2da8e0956d3b93ed34d/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L149-L161

# Окружение
Операционная система: Windows 11 Pro
IDE: Intellig IDEA Community Edition 2023.1
Java: Open JDK 11

**Comment by abashkaev** [comment]
Поправил метод, тест проходит
https://github.com/abashkaev/Team_project_JavaQA/blob/7b1c1c6aed1ff18fd8c579dc4df5a034cd11a8c1/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L72-L82

**Comment by Yliannasko** [comment]
По результатам тестирования метод Pay работает корректно
