### ISSUE TITLE
Не производиться расчет значения начисления в соответствии с заданным процентом если счет оставался неизменным в течении года

### ISSUE THREAD

**Issue by Yliannasko** [abashkaev/Team_project_JavaQA#6]
# Описание
Если счет оставался неизменным в течении года, то при расчете % на остаток результатом становиться сам %, а не значение соответствующее этому %

# Локация дефекта
https://github.com/abashkaev/Team_project_JavaQA/blob/e9bd6a6945b63f925c77cba1b0d0073004e63966/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L88

# Шаги воспроизведения
1. Открыть класс SevingAccountTest
2. Перейти к тесту shouldTestWhenBalanceNotChange
3. Создать объект SavingAccount класса со ставкой 
4. initialBalance =200,
    minBalance =200,
    maxBalance=10_000,
    rate =15,
5. Запуск теста на проверку ожидаемого результата balnce (200)/100*15

_Ожидаемый результат:_ Расчет размера начисления expected = 30
_Фактический результат:_ Расчет размера начисления actual = 15

# Вставка кода
     public void shouldTestWhenBalanceNotChange() {// расчет % на остаток если счет не менялся
        SavingAccount savingAccount = new SavingAccount(
                200,
                200,
                10_000,
                15
        );
        savingAccount.yearChange(false);
        int expected = 30;
        int actual = savingAccount.yearChange(false);
        Assertions.assertEquals(expected, actual);
    }

# Окружение
Операционная система: Windows 11 Pro
IDE: Intellig IDEA Community Edition 2023.1
Java: Open JDK 11

**Comment by abashkaev** [comment]
Необходимо переписать тесты  те, которые будут соответствовать ТЗ. Так же добавил в метод yearChange параметр для определения были ли какие либо изменения в течении года

https://github.com/abashkaev/Team_project_JavaQA/blob/3ca0f88566ae3db1be0fb65beeb0e2aa4008da73/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L122-L127

**Comment by Yliannasko** [comment]
Тест переписан на метод yearChange, если счет был неизменным.
https://github.com/abashkaev/Team_project_JavaQA/blob/62097f349a9f2f2c4046d2da8e0956d3b93ed34d/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L178-L190

**Comment by Yliannasko** [comment]
По результатам тестирования метод yearChange работает корректно

**Comment by Yliannasko** [comment]
По результатам тестирования метод yearChange работает успешно
