### ISSUE TITLE
Производиться расчет значения начисления не смотря на то, что счет изменялся в течении года

### ISSUE THREAD

**Issue by Yliannasko** [abashkaev/Team_project_JavaQA#7]
# Описание
Производится расчет % на остаток не смотря на то, что счет изменялся в течении года

# Локация дефекта
https://github.com/abashkaev/Team_project_JavaQA/blob/e9bd6a6945b63f925c77cba1b0d0073004e63966/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L88

# Шаги воспроизведения
1. Открыть класс SevingAccountTest
2. Перейти к тесту shouldTestWhenBalanceChange
3. Создать объект SavingAccount класса со ставкой 
4. initialBalance =3_000,
    minBalance =2_000,
    maxBalance=10_000,
    rate =15,
5. Запуск теста на проверку ожидаемого результата

_Ожидаемый результат:_  Начисление не производиться expected = 0
_Фактический результат:_ Расчет размера начисления actual = 3_000

# Вставка кода
    
  https://github.com/abashkaev/Team_project_JavaQA/blob/62097f349a9f2f2c4046d2da8e0956d3b93ed34d/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L192-L204

# Окружение
Операционная система: Windows 11 Pro
IDE: Intellig IDEA Community Edition 2023.1
Java: Open JDK 11

**Comment by abashkaev** [comment]
Необходимо переписать тесты на те, которые будут соответствовать ТЗ. Так же добавил в метод yearChange параметр для определения были ли какие либо изменения в течении года

https://github.com/abashkaev/Team_project_JavaQA/blob/3ca0f88566ae3db1be0fb65beeb0e2aa4008da73/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L122-L127

**Comment by Yliannasko** [comment]
Тест переписан для реализация метода, согласно условиям
https://github.com/abashkaev/Team_project_JavaQA/blob/62097f349a9f2f2c4046d2da8e0956d3b93ed34d/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L192-L205

**Comment by Yliannasko** [comment]
По результатам тестирования метод yearChange работает корректно.
