### ISSUE TITLE
Не корректное сообщение об ошибке, во время вызова ошибки с отрицательной процентной ставкой

### ISSUE THREAD

**Issue by abashkaev** [abashkaev/Team_project_JavaQA#8]
# Описание
При вызове ошибке, пользователю выводится сообщение "Накопительная ставка не может быть отрицательной, а у вас: ", но в данном классе процентная ставка является кредитной.

# Локация дефекта
https://github.com/abashkaev/Team_project_JavaQA/blob/258bf25cad2491e26d34b6ddf66250b8edd0ec0f/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L23

# Воспроизведение
1. Открыть код программы в IDEA
2. Создать объект типа CreditAccount,  у которого в переменной Rate указано отрицательное число
3. Запустить программу

ОР:  Ошибка, текст ошибки "Кредитная процентная ставка не может быть отрицательной, а у Вас: "  
ФР: Ошибка, текст ошибки  "Накопительная ставка не может быть отрицательной, а у вас: "  

# Тест
https://github.com/abashkaev/Team_project_JavaQA/blob/258bf25cad2491e26d34b6ddf66250b8edd0ec0f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L16-L18

#Окружение
IDE: IntelliJ IDEA 2023.1 (Community Edition) (Build #IC-231.8109.175, built on March 28, 2023)  
ОС: Windows 11 (22H2, 22621.1702)  
Java: OpenJDK11

**Comment by Yliannasko** [comment]
Тест ошибки при выкидывании исключения исправлен.
https://github.com/abashkaev/Team_project_JavaQA/blob/5b8338dc9e85038c8974f51191e6e17052890155/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L23

**Comment by abashkaev** [comment]
Все отлично! Спасибо
