### ISSUE TITLE
Отсутствует проверка движения счета, при начислении процентов

### ISSUE THREAD

**Issue by abashkaev** [abashkaev/Team_project_JavaQA#9]
# Описание
При начислении процентов по кредитному счету, отсутствует проверка было ли движении на счете.

# Локация дефекта
https://github.com/abashkaev/Team_project_JavaQA/blob/258bf25cad2491e26d34b6ddf66250b8edd0ec0f/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L74-L84

# Воспроизведение
1. Открыть код программы в IDEA
2. Создать объект типа CreditAccount, c отрицательным начальным балансом (-1000) и ставкой 15
3. Вызвать метод yearChange
4. Запустить программу

ОР: Ответ метода должен содержать информацию о том что счет менялся в течении года  
ФР: Выполняется расчет

# Окружение
IDE: IntelliJ IDEA 2023.1 (Community Edition) (Build #IC-231.8109.175, built on March 28, 2023)
ОС: Windows 11 (22H2, 22621.1702)
Java: OpenJDK11

**Comment by Yliannasko** [comment]
Внесены изменения в метод для проверки движения на счете. Необходимо внести поправки в тесты
https://github.com/abashkaev/Team_project_JavaQA/blob/406706018eca1e005447de16208c223d857112ca/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L101-L109

**Comment by abashkaev** [comment]
Задача закрыта, в виду отсутствия необходимости
